---
title: "MGSC 310 Final"
author: "Jenny Epstein and Wesley Ho"
subtitle: MGSC 310 Problem Set Template
output:
  html_document:
    df_print: paged
  html_notebook: default
---

```{r setup, include=FALSE}
# Please leave this code chunk as is. It makes some slight formatting changes to alter the output to be more aesthetically pleasing. 

library(knitr)

# Change the number in set seed to your own favorite number
set.seed(1818)
options(width=70)
options(scipen=99)


# this sets text outputted in code chunks to small
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=TRUE, size = "vsmall")  
opts_chunk$set(message = FALSE,                                          
               warning = FALSE,
               # "caching" stores objects in code chunks and only rewrites if you change things
               cache = FALSE,                               
               # automatically downloads dependency files
               autodep = TRUE,
               # 
               cache.comments = FALSE,
               # 
               collapse = TRUE,
               # change fig.width and fig.height to change the code height and width by default
               fig.width = 5.5,  
               fig.height = 4.5,
               fig.align='center')
```

```{r setup-2}
# Always print this out before your assignment
sessionInfo()
getwd()
```

```{r setup-3}
# Load libraries
library('tidyverse')
library('rsample')
library('glmnet')
library('glmnetUtils')
library('forcats')
```

```{r}
data <- read_csv("ds_salaries.csv")

# Create clean dataset removing salary, salary_currency, and job_title
# Factor most other variables
data_clean <- data %>% 
  mutate(any_remote = remote_ratio > 0,
         same_location = employee_residence == company_location,
         experience_level = as_factor(experience_level),
         employment_type = as_factor(employment_type),
         employee_residence = fct_lump(employee_residence, 6),
         company_location = fct_lump(company_location, 6),
         remote_ratio = as.factor(remote_ratio),
         work_year = as.factor(work_year),
         company_size = as.factor(company_size)) %>% 
  select(-salary, -salary_currency, -job_title, -`...1`)
# Re-order experience level factor for graphing purposes
data_clean$experience_level <- factor(data_clean$experience_level, levels = c("EN", "MI", "SE", "EX"))

# Export data
#write.csv(data_clean, "data_clean.csv", row.names = TRUE)
```

```{r}
# Experience level factors
levels(data_clean$experience_level)

# Employment type factors
levels(data_clean$employment_type)

# Remote ratio factors
levels(data_clean$remote_ratio)

# Company size factors
levels(data_clean$company_size)

# Work year factors
levels(data_clean$work_year)

# Employee residence factor - factor lump since there are many factors
levels(data_clean$employee_residence)

# Company location factor - factor lump since there are many factors
levels(data_clean$company_location)
```

```{r}
# Summary statistics
summary(data_clean)
```

```{r}
# Train/test split
data_split <- initial_split(data_clean, prop = 0.75)
data_train <- training(data_split)
data_test <- testing(data_split)
```

```{r}
# Shows salary increases on average with experience level
ggplot(data = data_clean, aes(x = experience_level, y = salary_in_usd, color = factor(remote_ratio))) +
  geom_point() +
  facet_wrap(~ remote_ratio) +
  labs(title = "Salary by Experience Level Grouped by Remote Ratio", x = "Experience Level", y = "Salary ($ USD)") +
  theme_minimal(base_size = 16)
```

```{r}
summary(data_clean$remote_ratio)
# Vast majority of data points are remote
ggplot(data = data_clean, aes(x = remote_ratio, fill = remote_ratio)) +
  geom_bar() +
  theme_minimal(base_size = 16) +
  labs(title = "Frequency of Remote/Hybrid/In-Person", x = "Remote Ratio", y = "Count")
```

```{r}
# Vast majority of data points are full-time
# Full-time, part-time, contract, freelancing
ggplot(data = data_clean, aes(x = employment_type, fill = remote_ratio)) +
  geom_bar() +
  theme_minimal(base_size = 16) +
  labs(title = "Frequency of Employment Type", x = "Employment Type", y = "Count")
```

```{r}
#create lasso model to identify the variables that impact salary_in_usd (training data)
lasso_mod <- cv.glmnet(salary_in_usd ~ . - any_remote,
                       data = data_train,
                       alpha = 1)
#print lambda min value
print(lasso_mod$lambda.min)
#print lambda 1se value
print(lasso_mod$lambda.1se)
#print lasso model
plot(lasso_mod)
#from this model, we can observe that a lambda min of 19 variables and a lambda 1se of 6 will give us the optimized range for to minimize cross-validated error in the prediction of salary_in_usd.
```
```{r}
#displays the penalization for variable weights -- sparse penalization between the factoring of variables makes it difficult to manually exclude variables. We will be trusting the lasso model to drop unnecessary variables. 
coef(lasso_mod, 
     s = lasso_mod$lambda.1se) %>% 
  round(3)
coef(lasso_mod, 
     s = lasso_mod$lambda.min) %>% 
  round(3)

```
```{r}
#display the variables selected when using lambda 1se
print(lasso_mod$lambda.1se)
#display the variables selected when using lambda min
print(lasso_mod$lambda.min)
```

---

```{r}
enet_mod <- cva.glmnet(any_remote ~ . - remote_ratio,
                       data = data_train,
                       alpha = seq(0,1, by = 0.05),
                       family = "binomial")
plot(enet_mod)
```

```{r}
# Really wants to be LASSO
minlossplot(enet_mod, 
            cv.type = "min")
```

```{r}
get_alpha <- function(fit) {
  alpha <- fit$alpha
  error <- sapply(fit$modlist, 
                  function(mod) {min(mod$cvm)})
  alpha[which.min(error)]
}

get_model_params <- function(fit) {
  alpha <- fit$alpha
  lambdaMin <- sapply(fit$modlist, `[[`, "lambda.min")
  lambdaSE <- sapply(fit$modlist, `[[`, "lambda.1se")
  error <- sapply(fit$modlist, function(mod) {min(mod$cvm)})
  best <- which.min(error)
  data.frame(alpha = alpha[best], lambdaMin = lambdaMin[best],
             lambdaSE = lambdaSE[best], eror = error[best])
}

# extract the best alpha value and model parameters
best_alpha <- get_alpha(enet_mod)
print(best_alpha)
get_model_params(enet_mod)

# extract the best model object
best_mod <- enet_mod$modlist[[which(enet_mod$alpha == best_alpha)]]
plot(best_mod)
print(best_mod)
print(best_mod$lambda.min)
```

```{r}
coef(best_mod)
```

